name: Autograding Action
description:  Action that autogrades assignments based on configurable quality critera.


inputs:
  CONFIG:
    description: "Autograding configuration"
    required: false
    default: "/default.conf"
  TOKEN:
    description: "GitHub token"
    required: true
  DEBUG:
    description: "Enable logging"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CONFIG: ${{ inputs.CONFIG }}
    TOKEN: ${{ inputs.TOKEN }}
    DEBUG: ${{ inputs.DEBUG }}

branding:
  icon: check
  color: red
