name: Java CI with Maven
description:  Autograding action.

inputs:
  DEBUG:
    description: "Debug on/off"
    required: false
    default: "false"
  CONFIG:
    description: "Autograding config"
    required: false
    default: ""
  TOKEN:
    description: "GitHub token"
    required: false
    default: ""

runs:
  using: node12
  main: entrypoint.sh