name: Java CI with Maven
description:  Autograding action.


inputs:
  CONFIG:
    description: "Autograding config"
    required: false
    default: "/default.conf"
  TOKEN:
    description: "GitHub token"
    required: true
    default: ""
  DEBUG:
    description: "Debug on/off"
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CONFIG: ${{ inputs.CONFIG }}
    TOKEN: ${{ inputs.TOKEN }}
    DEBUG: ${{ inputs.DEBUG }}

branding:
  icon: check
  color: red