name: Autograding Action
description:  Action that autogrades assignments based on configurable quality critera.

inputs:
  CONFIG:
    description: "Autograding configuration"
    required: false
  TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CONFIG: ${{ inputs.CONFIG }}
    TOKEN: ${{ inputs.TOKEN }}
    HEAD_SHA: ${{ inputs.HEAD_SHA }}

branding:
  icon: check
  color: red
