name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: actions/checkout@v2
      - name: Set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Build with maven
        run: mvn test -B package --file pom.xml -Dmaven.test.failure.ignore=true
      - name: Get report
        run: echo "::set-env name=REPORT::$(echo $(java -jar out/artifacts/github_actions_autograding_jar/github-actions-autograding.jar))"
      - name: Comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: output.txt