name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.202' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: actions/checkout@v2
      - name: Set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven (junit, checkstyle, findbugs, pmd)
        run: mvn -ntp -V -e clean verify -Dmaven.test.failure.ignore -Dgpg.skip
      - name: Build with maven (pit)
        run: mvn -ntp org.pitest:pitest-maven:mutationCoverage
        continue-on-error: true
      - name: Build with maven (jacoco)
        run: mvn -ntp -V -U -e jacoco:prepare-agent test jacoco:report -Dmaven.test.failure.ignore
      - name: Get reports
        run: java -jar out/artifacts/github_actions_autograding_jar/github-actions-autograding.jar test ${{ secrets.GITHUB_TOKEN }}