name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up jdk
        uses: actions/setup-java@v1
        with:
          java-version: 1.13
      - name: Build with maven
        run: mvn -B package --file pom.xml
      - name: Get report
        run: echo "::set-env name=REPORT::$(cat target/surefire-reports/de.tobiasmichael.me.MyTest.txt | sed "s/\n/%0A/")" && echo ${{ env.REPORT }}
      - name: Comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: ${{ env.REPORT }}
          check_for_duplicate_msg: false  # OPTIONAL